sudo: false
language: node_js
node_js:
- '8'
services:
- docker
cache:
  directories:
  - google-cloud-sdk
  - node_modules
env:
  global:
    - GCLOUD_PROJECT=telegram-bot
    - PORT=80
before_install:
- openssl aes-256-cbc -K $encrypted_f854e4dcb63b_key -iv $encrypted_f854e4dcb63b_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d
- tar -xzf credentials.tar.gz
- gcloud auth activate-service-account --key-file client-secret.json
install:
- npm install
script:
- npm test
before_deploy:
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export
  CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
- source /home/travis/google-cloud-sdk/path.bash.inc
- gcloud --quiet version
- gcloud --quiet components update
deploy:
  provider: gcs
  access_key_id: ${GCS_ACCESS_KEY_ID}
  secret_access_key:
    secure: kyt9q4JUYJrXJ7g/n85BL3Yy+Q9e/Vu0ZGlXwA8EzIBwXWd5o3ZIKVLCkWeSeulbD59cTJp5clSnuOPP8uctO62uaFnk1Iw+iqx9PejViI5aqkG9J7Kjo03FWRbhPof4jbjJUU2TG/pk2wCaTx/EQcvbMwfACLqzplD5dkoUIDA52lzbkqRXMoT/cR8N7NJ3P0rJnn51cEtqCLYhoCRB1YIXG3JuX7lHaGh3I0mlN8QO6VLWYa9GS6UBPLqv7DnaTvf1q+Dpk0SGmsu5DSFC3uL4RJDC1+gMgOQ+wPpbU+6IPxmTJ1YcL+bpJZDMofdLYb4Qk9stXjEkA42WRgifX09TH5D2ge0qecdntt5GJNazsW2hEccRjRFTX/aeFtEW2zubnxoTv5s/EyvTpml4VurvYpCS4k8808H1yLv0q9eyppf/jEbw1Ub/JWVOQgIaVRTrXUblwnJhnMNz5mTsFKrzT3Mxwnwz7yYv7jJoOF7WkIEiwx0UOPLlZi14yJ8zWF+mBuJbIK/TN0gCcyuQS8Vq7lEuw6dwpr7UeAXKOOrVeKpk+QaZ4uYPeJ1MUhvepqk2uSCdv1iJ+jkV42H26R5wcLWEW0RpvJ6P2biebCBFi/S2Frm95HJ6MF1Klt/HCBMk4EX5s/nOCc+sgYpAegPgdw+KM82a3pGnLNZL1Q4=
  bucket: GCS Bucket
  local-dir: workdir
  skip_cleanup: true
  on:
    repo: nmoya/telegram-bot
