sudo: false
language: node_js
node_js:
- '8'
services:
- docker
cache:
  directories:
  - $HOME/google-cloud-sdk/
  - node_modules
env:
  global:
    - GCLOUD_PROJECT=telegram-bot
    - PORT=80
before_install:
- openssl aes-256-cbc -K $encrypted_f854e4dcb63b_key -iv $encrypted_f854e4dcb63b_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d
- gcloud auth activate-service-account --key-file client-secret.json
install:
- npm install
script:
- npm test
before_deploy:
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export
  CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
- source /home/travis/google-cloud-sdk/path.bash.inc
- gcloud --quiet version
- gcloud --quiet components update
- gcloud --quiet components beta update
deploy:
- npm start
